services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.nicoshl.de"
    volumes:
      - /mnt/CrazyBigStorage/Container/Vaultwarden/data:/data
    networks:
      - r_proxy

networks:
  r_proxy:
    external: true