services:
  cloudflare:
    image: oznu/cloudflare-ddns:latest
    container_name: Cloudflare
    restart: unless-stopped
    environment:
      - API_KEY=${API_KEY}
      - ZONE=nicoshl.de
      - SUBDOMAIN=vpn
      - PROXIED=false
      - RRTYPE=A
