services:
  samba:
    image: dperson/samba
    container_name: Share
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /mnt/Storage/Longterm:/Longterm
      - /mnt/Storage/Workspace:/Workspace
    environment:
      - USER=nico;${SAMBA_PASSWORD}
      - SHARE=Longterm;/Longterm;yes;no;no;nico;nico
      - SHARE2=Workspace;/Workspace;yes;no;no;nico;nico
      - RECYCLE=true
      - PERMISSIONS=true
      - TZ=Europe/Berlin
