services:
  backrest:
    image: garethgeorge/backrest
    container_name: Backrest
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - /mnt/Storage:/source   # deine Container-Daten (read-only)
      - ~/Backup:/repo                   # Ziel für die Backups
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    ports:
      - 9898:9898
    restart: unless-stopped
